<?php
$isEdit = $mode === 'edit';
$title  = $isEdit ? $this->te('Group Settings') : $this->te('Add Group');
$this->headTitle()->set($title);

$canDelete = $this->permissions()->isOne(array('super', 'owner' => $group));

// scope name editing restrictions to edit mode only
$canEditName = !$isEdit || $canEditName;

// when editing, show the sidebar
echo '<div class="row-fluid">';
echo $this->groupSidebar($group);

?>
<div class='span9 profile-body group-edit'>
<?php
    // when editing, we like to show the toolbar and sidebar
    if ($isEdit) {
     echo $this->groupToolbar($group);
    }
?>
    <h1><?php echo $this->te($title) ?></h1>
    <form method="post" class="form-horizontal form">
        <?php include __DIR__ . '/settingsForm.phtml' ?>
        <div class="control-group group-buttons">
            <div class="controls">
                <button type="submit" class="btn btn-mlarge btn-primary"><?php echo $this->te('Save')?></button>
                <button type="button" class="btn btn-mlarge" onclick="window.history.back(); return false;"><?php echo $this->te('Cancel')?></button>
                <?php if ($isEdit && $canDelete): ?>
                    <button type="button" class="btn btn-mlarge btn-danger btn-delete"><?php echo $this->te('Delete')?></button>
                <?php endif; ?>
            </div>
        </div>
    </form>
    <?php
$actionUrl = $isEdit
    ? '/group/' . $this->escapeUrl($group->getId()) . '/settings/'
    : '/group/add';
?>
    <script type="text/javascript">
        swarm.group.initEdit(
            '.group-edit',
            '<?php echo $this->escapeJs($actionUrl) ?>',
            '<?php echo $group->getId() ?>'
        );
    </script>
</div>
</div>
