<?php
$this->headTitle()->set($group->getConfig()->getName())->setTranslatorEnabled(false);
$this->bodyClass()->append('login-reload');
?>

<div class="row-fluid">
    <?php echo $this->groupSidebar($group) ?>
    <div class="span9 profile-body group-edit">
        <?php echo $this->groupToolbar($group) ?>
        <div>
            <form id="notificationForm" method="post" class="form-horizontal form">
                <?php include __DIR__ . '/notificationsForm.phtml' ?>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
$(function(){
// truncate the description
$('.group-sidebar .description').expander({slicePoint: 250});
});
swarm.group.initEdit(
    '.group-edit',
    '/group/<?php echo $this->escapeHtml($group->getId())?>/notifications/',
    '<?php echo $group->getId() ?>'
);
// Configure the settings form controls
swarm.settings.group.init();
</script>