<?php
$this->headTitle()->set($this->te("Dashboard"));
?>

    <div id="actionable-reviews" class="dashboard tab-pane fade">
        <div class="header" id="actionable-reviews-header">
            <h2><?php echo $this->te("Reviews to act on"); ?></h2>
            <p><?php echo $this->te(
"Reviews you are participating in that need your vote, reviews that you authored that need changes, and reviews on " .
"branches where you're a moderator that you should approve or reject"
                ); ?></p>
        </div>
        <div class="toolbar button-toolbar row-fluid" id="actionable-reviews-filter-bar">
            <div class="span7">
                <div class="btn-group">
                    <div class="btn-group group-radio" data-filter-key="project">
                        <button type="button" disabled="disabled" class="btn btn-project dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" title="<?php echo $this->te("Project")?>">
                            <i class="icon-project swarm-icon"></i>
                            <span class="text"><?php echo $this->te("All Projects")?></span> <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu" aria-label="All Projects">
                            <li><a href="#" class="btn-filter default active" data-filter-value=""><?php echo $this->te("All Projects")?></a></li>
                            <li><a href="#" class="btn-filter" data-filter-value="<?php echo implode(", ",$myProjects) ?>"><?php echo $this->te("My Projects")?></a></li>
                            <li class="divider"></li>
                        </ul>
                    </div>
                </div>
                <div class="btn-group group-radio" data-filter-key="role">
                    <button type="button" disabled="disabled" class="btn btn-project dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" title="<?php echo $this->te("Role")?>">
                        <i class="icon-user"></i>
                        <span class="text"><?php echo $this->te("All Roles")?></span> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-label="All Roles">
                        <li><a href="#" class="btn-filter default active" data-filter-value=""><?php echo $this->te("All Roles")?></a></li>
                        <li class="divider"></li>
                    </ul>
                </div>
                <div class="btn-group">
                    <div class="input-group">
                        <input id="author-filter-value" type="text" disabled="disabled" class="typeahead" data-filter-key="author" placeholder="<?php echo $this->te("Authored by")?>">
                    </div>
                </div>
            </div>
            <div class="span5 text-right">
                <div class="btn-group btn-user">
                    <button type="button" id="reset-filter-values" disabled="disabled" title="<?php echo $this->te("Reset")?>" class="btn" aria-label="Reset" data-filter-value="reset" data-original-title="<?php echo $this->te("Reset")?>">
                        <i class="icon-repeat"></i>
                        <span class="text"><?php echo $this->te("Reset")?></span>
                    </button>
                </div>
                <div class="btn-group">
                    <div class="input-group">
                        <div class="input-prepend search">
                            <span class="add-on"><i class="icon-search"></i></span>
                            <input id="search-filter-value" type="text" disabled="disabled" placeholder="<?php echo $this->te("Search")?>">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="actionable-review-panel">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th class="author"><?php echo $this->te("Author"); ?></th>
                    <th class="id"><?php echo $this->te("ID"); ?></th>
                    <th class="description"><?php echo $this->te("Description"); ?></th>
                    <th class="project-branch"><?php echo $this->te("Project(s)"); ?></th>
                    <th class="role"><?php echo $this->te("Your role"); ?></th>
                    <th class="state"><?php echo $this->te("State"); ?></th>
                    <th class="votes center" title="<?php echo $this->te("Votes up/down"); ?>"><i class="icon-chevron-up"></i>/<i class="icon-chevron-down"></i></th>
                    <th class="updated"><?php echo $this->te("Last activity"); ?></th>
                </tr>
                </thead>
                <tbody>
                <tr><td colspan="8"><div class="loading animate"><?php echo $this->te("Loading..."); ?></div></td></tr>
                </tbody>
            </table>
        </div>
        <script type="text/javascript">
            $('#projects-column table').on('loaded',function(){
                swarm.dashboard.init('#actionable-review-panel');
                swarm.dashboard.openTab();
            });
        </script>
    </div>