<?php
$this->headTitle()->set($project->getName())->setTranslatorEnabled(false);
$this->bodyClass()->append('login-reload');
$baseUrl      = $this->escapeFullUrl($this->assetBasePath());
$config       = $this->getHelperPluginManager()->getServiceLocator()->get('config');
echo $this->projectToolbar($project, $readme);
?>

<div class="row-fluid">
    <?php echo $this->projectSidebar($project); ?>
    <div class="span9 profile-body">
        <?php if (empty($readme)) {
            echo "<div>" . $this->activity('project-' . $project->getId()). "</div>"; ?>
            <script type="text/javascript">
                $('.project-navbar li:first').addClass('active');
            </script>
  <?php } else { ?>
        <div class="project-readme">
            <div class="pad2">
                <div class="view view-md markdown">
                    <?php echo $readme; ?>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
</div>
